Templates supplier
ITA-Dnipro/Dp-218_Go pull request #40
Opened 2021-12-22 15:27 UTC by goRoman1

Working templates on supplier

2021-12-22 17:00 UTC, DmytroTHR requested changes
**Wrong branch!** You should merge to "develop" not "main".
Don't forget to `git pull origin develop` into your branch & resolve conflicts if there would be any. Then make PR on "develop".

2021-12-22 17:09 UTC, goRoman1 reviewed
branch to merge has been changed

2021-12-22 17:35 UTC, DmytroTHR commented on migrations/roma.up.sql
> +CREATE TABLE IF NOT EXISTS roles
Do we need this file in develop?

2021-12-22 17:40 UTC, DmytroTHR approved these changes
Check if we need roma.sql file in migration

2021-12-22 21:40 UTC, useralexey2000 commented on migrations/roma.up.sql
> +CREATE TABLE IF NOT EXISTS roles
agree

2021-12-22 21:42 UTC, useralexey2000 commented on routing/supplier.go
> +		Uri:     `/delete/{id}`,
too ambiguous. previous name was better as for me

2021-12-22 21:50 UTC, useralexey2000 approved these changes

2021-12-23 10:54 UTC, merged

2021-12-23 11:04 UTC, OlegovichAndrew commented on repositories/supplier.go
> +//go:generate mockgen -source=supplier.go -destination=../repositories/mocks/mock_supplier_repository.go -package=mock
I guess we should use only singular names of folders. Like in Golang code-style.
'mock' instead of -> 'mocks'