Kyrylo
ITA-Dnipro/Dp-218_Go pull request #7
Opened 2021-12-07 15:03 UTC by xioru

Scooter station changes

2021-12-07 16:36 UTC, DmytroTHR commented on docker-compose.yml
> +    #volumes:
no need to change this file, I think

2021-12-07 16:37 UTC, DmytroTHR commented on go.mod
>  require (
no need to change this file, I think

2021-12-07 16:37 UTC, DmytroTHR commented on go.sum
>  github.com/denisenkom/go-mssqldb v0.10.0/go.mod h1:xbL0rPBG9cCiLr28tMa8zpbdarY27NDyej4t/EjAShU=
no need to change this file, I think

2021-12-07 16:37 UTC, DmytroTHR commented on repositories/postgres/user.go
>  	for rows.Next() {
no need to change this file, I think

2021-12-07 16:42 UTC, DmytroTHR requested changes
There shouldn't be files marked with my recent comments, I think. Try to pull the last develop once again and merge it with your branch (replacing marked files in your branch to ones 
 from develop).

2021-12-09 16:34 UTC, IntelliJIN requested changes
Please add comments to structures and methods/functions.

2021-12-13 15:39 UTC, closed without merging